feat: add Chinese Translation
iscas-tis/chisel-formal-verification pull request #1
Opened 2024-06-24 09:19 UTC by SeddonShen

2024-07-01 02:36 UTC, liuyic00 requested changes
有一些问题需要修改，见上面。

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +  - [NutShell](#nutshell)
“## 目录”，并且用`<!-- omit in toc -->`不在自动生成的目录中显示
目录使用vscode插件markdown all in one生成，请自动生成，现在的格式不对，不支持跳转

2024-07-01 02:36 UTC, liuyic00 commented on README.md
> +[简体中文](./README_CN.md) [English](./README.md)
下面应该有一个空行，请使用markdownlint检查markdown语法，并解决报错
另一个文件里也有报错，请一起处理

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +[riscv-spec-core](https://github.com/iscas-tis/riscv-spec-core) 设计了一个参考模型，使用形式化语义来描述RISC-V ISA文档。
参考模型并不是形式化描述的，所以英文版只说是用参考模型***当作***ISA的形式化语义。不过英文这种说法感觉也不合适，可以说”...使用一个参考模型来表示 RISC-V 指令集规范文档的语义“，不提形式化了。

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +使用Chisel设计处理器需要与参考模型保持严格的一致性，工具中还提供了帮助参考模型和处理器设计之间实现信号同步的部分。
“待验证的 Chisel 处理器设计应该和参考模型的功能一致。项目中还提供了帮助在参考模型和处理器设计间进行信号同步的工具。”

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +经验证的NutShell仓库见： [nutshell-fv](https://github.com/iscas-tis/nutshell-fv).
请在中英文之间添加空格。“经验证的 NutShell 仓库见”。其他地方同理。

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +在这个处理器设计的例子中，我们使用了工具链中的参考模型[riscv-spec-core](https://github.com/iscas-tis/riscv-spec-core)，并通过[ChiselTest](https://github.com/ucb-bar/chiseltest)调用了BMC算法进行形式化验证。
“我们使用了工具链中的 [riscv-spec-core](https://github.com/iscas-tis/riscv-spec-core) 组成了一个包含参考模型和性质的可验证的系统”

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +[CHA](https://github.com/iscas-tis/CHA) 提供了针对 Chisel 程序的断言语言和验证工具，它建立在 ChiselTest 的基础上，并使用用类似于 SystemVerilog 断言（SVA）的时序运算符扩展了 Chisel 断言语言。
“[CHA](https://github.com/iscas-tis/CHA) 是一个建立在 ChiselTest 上的针对 Chisel 程序的断言语言和验证工具，其中使用类似于 SystemVerilog 断言（SVA）的时序运算符扩展了 Chisel 断言语言。”

2024-07-01 02:36 UTC, liuyic00 commented on README_CN.md
> +这使得 Chisel 硬件设计可以根据一般时态属性进行形式验证。
“可以对 Chisel 硬件设计和一般时序性质进行形式化验证。”

2024-07-01 03:12 UTC, SeddonShen commented
全部修改完啦～

2024-07-01 05:18 UTC, liuyic00 requested changes
漏掉的一些

2024-07-01 05:18 UTC, liuyic00 commented on README_CN.md
> +### RISC-V Spec Core: RISC-V指令集一致性验证工具
```suggestion
### RISC-V Spec Core: RISC-V 指令集一致性验证工具
```

2024-07-01 05:18 UTC, liuyic00 commented on README_CN.md
> +## 工具集合
全叫工具链好了

```suggestion
## 工具链
```

2024-07-01 05:18 UTC, liuyic00 commented on README_CN.md
> +    - [NutShell](#nutshell)
这个要从h2开始生成，即不生成Chisel Formal Verification这条目录。
在插件设置里可以改，Markdown › Extension › Toc: Levels 2..6。
英文版同理，被插件自动改掉了

2024-07-01 05:18 UTC, liuyic00 commented on README_CN.md
> +## 仓库内容 <!-- omit in toc -->
```suggestion
## 目录 <!-- omit in toc -->
```

2024-07-01 05:18 UTC, liuyic00 commented on README_CN.md
> +在这个处理器设计的例子中，我们使用了工具链中的[riscv-spec-core](https://github.com/iscas-tis/riscv-spec-core)组成了一个包含参考模型和性质的可验证的系统，并通过[ChiselTest](https://github.com/ucb-bar/chiseltest)调用了 BMC 算法进行形式化验证。
```suggestion
经验证的 NutShell 仓库见：[nutshell-fv](https://github.com/iscas-tis/nutshell-fv)。

在这个处理器设计的例子中，我们使用了工具链中的 [riscv-spec-core](https://github.com/iscas-tis/riscv-spec-core) 组成了一个包含参考模型和性质的可验证的系统，并通过 [ChiselTest](https://github.com/ucb-bar/chiseltest) 调用了 BMC 算法进行形式化验证。
```

2024-07-01 05:18 UTC, liuyic00 commented on README.md
> +    - [NutShell](#nutshell)
插件问题，见中文文档评论

2024-07-02 02:14 UTC, SeddonShen commented
可以合并了应该

2024-07-02 02:57 UTC, liuyic00 approved these changes

2024-07-02 02:58 UTC, merged